version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./config:/config
    restart: unless-stopped